export const MODULES = {
  //  authentication Modules
  USER: "USER",
  ROLE: "ROLE",
  PERMISSION: "PERMISSION",
  TENANT: "TENANT",
  SUBSCRIPTION_PLAN : "SUBSCRIPTION_PLAN",
  ABOUT: "ABOUT",
  RESUME: "RESUME", 
  PORTFOLIO: "PORTFOLIO",
  CONTACT: "CONTACT",
  QUERY: "QUERY",
  VISIT_TRACK: "VISIT_TRACK",
};
