export const MODULES = {
  //  authentication Modules
  USER: "USER",
  ROLE: "ROLE",
  PERMISSION: "PERMISSION",
  TENANT: "TENANT",

  ABOUT: "ABOUT",
  RRESUME: "RESUME",
  PORTFOLIO: "PORTFOLIO",
  CONTACT: "CONTACT",
  QUERY: "QUERY",
  VISIT_TRACK: "VISIT_TRACK",
};
